# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6587171b9f280286db81c8eeb42ff2992223588df9a25b1cbc95fd7b8660bf31f22daa429c6b69e1acdbd19d5fa60beed08fdab4daf91fed84f648a8dba17823

test:
  secret_key_base: 3c258445e9a562941f21e3a20acdbcac8ecd06efeeeb275dd2753183c7110cb596446f4d3f535bef5eb2d44784d16c2e3a487acb8a6890b7d477f6f0c347d7df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
